
version: "3"
services:
  backend:
    container_name: uda-backend
    image: uda/backend:latest
    ports:
    - "3000:3000"
    env_file:
    - backend/.env
    depends_on:
    - postgres
    networks:
    - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    env_file:
    - backend/.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge