version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build-backend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Build backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-backend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Test backend
          command: |
            cd backend
            npm install
            npm run test

  lint-backend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run:
          name: Lint backend
          command: |
            cd backend
            npm install
            npm run lint

  build-frontend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  test-frontend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm install
            npm run test

  lint-frontend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Lint frontend
          command: |
            cd frontend
            npm install
            npm run lint

  lint-docker:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            wget -O ~/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x ~/hadolint
      - run:
          name: Lint dockerfile backend
          command: |
            cd backend
            ~/hadolint Dockerfile
      - run:
          name: Lint dockerfile frontend
          command: |
            cd frontend
            ~/hadolint Dockerfile

workflows:
  default:
    jobs:
      - lint-backend
      - build-backend:
          requires: [lint-backend]
      - test-backend:
          requires: [build-backend]

      - lint-frontend
      - build-frontend:
          requires: [lint-frontend]
      - test-frontend:
          requires: [build-frontend]
      - lint-docker



