version: 2.1

jobs:
  build-backend:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run: node --version      
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Build backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build      

workflows:
  default:
    jobs:
      - say-hello
